server:
  port: ${SERVICE_PORT:8082}
spring:
  application:
    name: carson-cloud-product
  profiles:
    active: ${SPRING_PROFILE:dev}
  jackson:
    serialization:
      write-dates-as-timestamps: true
  datasource:
     driver-class-name: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/product?useUnicode=true&characterEncoding=utf-8&useSSL=false
     username: root
     password: adminbp
  jpa:
     hibernate:
        database-platform: org.hibernate.dialect.MySQLDialect
        ddl-auto: update
        show-sql: true
logging:
  file:
    name: ${logging.file.path}/application.log
    path: /log/${spring.application.name}
  level:
    root: info
eureka:
   instance:
      preferIpAddress: true		#注册服务的IP，而不是服务器的名称
      client: 
         registerWithEureka: true	#向Eureka注册服务
         fetchRegistry: true		#拉取注册表的本副本
         serviceUrl: 
            defaultZone: http://localhost:8761/eureka/    